default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  # Set username and password in secrets.yml
  username: <%= Rails.application.secrets[:database][:user] %>
  password: <%= Rails.application.secrets[:database][:password] %>

development:
  <<: *default
  database: recycle_development

test:
  <<: *default
  database: recycle_test

production:
  <<: *default
  database: recycle_production
  username: recycle-bg
  password: <%= ENV['RECYCLE_DATABASE_PASSWORD'] %>
